// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	context "context"

	core "github.com/stackus/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/stackus/edat/msg"
)

// CommandMessagePublisher is an autogenerated mock type for the CommandMessagePublisher type
type CommandMessagePublisher struct {
	mock.Mock
}

// PublishCommand provides a mock function with given fields: ctx, replyChannel, command, options
func (_m *CommandMessagePublisher) PublishCommand(ctx context.Context, replyChannel string, command core.Command, options ...msg.MessageOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, replyChannel, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, core.Command, ...msg.MessageOption) error); ok {
		r0 = rf(ctx, replyChannel, command, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
