// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	core "github.com/stackus/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/stackus/edat/msg"
)

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

// Command provides a mock function with given fields:
func (_m *Command) Command() core.Command {
	ret := _m.Called()

	var r0 core.Command
	if rf, ok := ret.Get(0).(func() core.Command); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Command)
		}
	}

	return r0
}

// Headers provides a mock function with given fields:
func (_m *Command) Headers() msg.Headers {
	ret := _m.Called()

	var r0 msg.Headers
	if rf, ok := ret.Get(0).(func() msg.Headers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msg.Headers)
		}
	}

	return r0
}
