// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// CommandDispatcherOption is an autogenerated mock type for the CommandDispatcherOption type
type CommandDispatcherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: consumer
func (_m *CommandDispatcherOption) Execute(consumer *msg.CommandDispatcher) {
	_m.Called(consumer)
}
