// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	context "context"

	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// Close provides a mock function with given fields: ctx
func (_m *Consumer) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Listen provides a mock function with given fields: ctx, channel, consumer
func (_m *Consumer) Listen(ctx context.Context, channel string, consumer msg.ReceiveMessageFunc) error {
	ret := _m.Called(ctx, channel, consumer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, msg.ReceiveMessageFunc) error); ok {
		r0 = rf(ctx, channel, consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
