// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import mock "github.com/stretchr/testify/mock"

// DomainCommand is an autogenerated mock type for the DomainCommand type
type DomainCommand struct {
	mock.Mock
}

// CommandName provides a mock function with given fields:
func (_m *DomainCommand) CommandName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DestinationChannel provides a mock function with given fields:
func (_m *DomainCommand) DestinationChannel() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
