// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// EntityEventDispatcherOption is an autogenerated mock type for the EntityEventDispatcherOption type
type EntityEventDispatcherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: consumer
func (_m *EntityEventDispatcherOption) Execute(consumer *msg.EntityEventDispatcher) {
	_m.Called(consumer)
}
