// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// EventDispatcherOption is an autogenerated mock type for the EventDispatcherOption type
type EventDispatcherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: consumer
func (_m *EventDispatcherOption) Execute(consumer *msg.EventDispatcher) {
	_m.Called(consumer)
}
