// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	context "context"

	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, message
func (_m *MessagePublisher) Publish(ctx context.Context, message msg.Message) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, msg.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
