// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// MessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MessageSubscriber struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: channel, receiver
func (_m *MessageSubscriber) Subscribe(channel string, receiver msg.MessageReceiver) {
	_m.Called(channel, receiver)
}
