// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// PublisherOption is an autogenerated mock type for the PublisherOption type
type PublisherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *PublisherOption) Execute(_a0 *msg.Publisher) {
	_m.Called(_a0)
}
