// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	core "github.com/stackus/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/stackus/edat/msg"
)

// Reply is an autogenerated mock type for the Reply type
type Reply struct {
	mock.Mock
}

// Headers provides a mock function with given fields:
func (_m *Reply) Headers() msg.Headers {
	ret := _m.Called()

	var r0 msg.Headers
	if rf, ok := ret.Get(0).(func() msg.Headers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msg.Headers)
		}
	}

	return r0
}

// Reply provides a mock function with given fields:
func (_m *Reply) Reply() core.Reply {
	ret := _m.Called()

	var r0 core.Reply
	if rf, ok := ret.Get(0).(func() core.Reply); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Reply)
		}
	}

	return r0
}
