// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/stackus/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// SubscriberOption is an autogenerated mock type for the SubscriberOption type
type SubscriberOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SubscriberOption) Execute(_a0 *msg.Subscriber) {
	_m.Called(_a0)
}
